import jetPaths from 'jet-paths';

const Paths = {
  _: '/api',
  Users: {
    _: '/users',
    StatsOverview: '/stats/overview/:userId',
    StatsLocations: '/stats/locations/:userId',
    StatsTopProducts: '/stats/top-products/:userId',
    StatsMonthly: '/stats/monthly/:userId',
    StatsStatusBreakdown: '/stats/status-breakdown/:userId',
    StatsRecentSales: '/stats/recent-sales/:userId',
    StatsSellerOverview: '/stats/seller/overview/:userId',
    StatsSellerMonthly: '/stats/seller/monthly/:userId',
    StatsSellerTopDebtors: '/stats/seller/top-debtors/:userId',
    StatsShipperOverview: '/stats/shipper/overview/:userId',
    StatsShipperMonthly: '/stats/shipper/monthly/:userId',
    Get: '/all',
    GetOne: '/:id',
    Add: '/add',
    Search: '/search',
    Update: '/update',
    Delete: '/delete/:id',
    Login: '/login',
  },
  Products: {
    _: '/products',
    Get: '/all',
    GetOne: '/:id',
    Add: '/add',
    Update: '/update',
    Delete: '/delete/:id',
  },
  Locations: {
    _: '/locations',
    Get: '/all',
    GetOne: '/:id',
    Add: '/add',
    Update: '/update',
    Delete: '/delete/:id',
    SyncCanTho: '/sync/can-tho',
  },
  Customers: {
    _: '/customers',
    Get: '/all',
    GetOne: '/:id',
    Add: '/add',
    Update: '/update',
    Delete: '/delete/:id',
    Account: '/:id/account',
    ReceivePayment: '/:id/receive-payment',
  },
  Invoices: {
    _: '/invoices',
    Get: '/all',
    GetOne: '/:id',
    Add: '/add',
    Update: '/update',
    Delete: '/delete/:id',
  },
  Activities: {
    _: '/activities',
    Get: '/all',
    GetOne: '/:id',
    Add: '/add',
    Update: '/update',
    Delete: '/delete/:id',
    Confirm: '/:id/confirm',
    AdvanceStatus: '/:id/advance-status',
    DetailsGet: '/:activityId/details',
    DetailsAdd: '/details/add',
    DetailsUpdate: '/details/update',
    DetailsDelete: '/details/delete/:activityId/:productId',
    PaymentSummary: '/:activityId/payment-summary',
    PaymentsList: '/:activityId/payments',
    PaymentsApplyBalance: '/:activityId/payments/apply-balance',
    PaymentsAdd: '/:activityId/payments',
    PaymentsDelete: '/payments/:paymentId',
  },
  OrderStatuses: {
    _: '/order-statuses',
    Get: '/all',
  },
  Auth: {
    _: '/auth',
    Login: '/login',
    Refresh: '/refresh',
    Logout: '/logout',
    Register: '/register',
    Check: '/check',
    VerifyEmail: '/verify-email',
  },
  Salaries: {
    _: '/salaries',
    GetAll: '/all',
    GetByUserId: '/user/:userId',
    GetOne: '/:id',
    Add: '/add',
    Update: '/update',
    Delete: '/delete/:id',
  },
} as const;

export const JetPaths = jetPaths(Paths);
export default Paths;
